### ISSUE TITLE
Implement personRepository and personService methods to update existing accounts

### ISSUE THREAD

**Issue by elkhjean** [RobertFuruvald/IV1201#21]
Implement functions inside repository and service for "Person" to update existing accounts.

**Comment by Nariman-Haidar** [comment]
Jag jobbar på denna

**Comment by narimanhaidar** [comment]
Jag jobbar på denna

**Comment by narimanhaidar** [comment]
Now its done

**Comment by elkhjean** [comment]
Several issues with implementation. Does not follow use case

**Comment by elkhjean** [comment]
Identified problems:
-Does not adhere to the plan for data migration
-Incomplete users does not have username, using it to find users will fail. Search should be made with email.
-No Transactional statement in service. Operation is not transaction safe
-Violates DRY (do not repeat yourself) principal by implementing redundant code
-Doesn't follow validation practice used in the rest of the codebase

**Comment by narimanhaidar** [comment]
I updated the person services and now it follows these steps:
The method now finds users by email instead of username to avoid failures for incomplete users.
@Transactional annotation is added to ensure the operation is transaction-safe.
The updatePersonFields method is introduced to refactor and avoid redundant code.
The code now follows the validation practices used in the rest of the codebase.
